---
geometry: "left=1cm,right=1cm,top=1cm,bottom=1cm"
header-includes:
output: pdf_document
---

```{r setup0, echo=FALSE,purl=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

**Question 1**

```{r}
pval1 <- 1 - pt(2.01, df = 20)
pval2 <- 2 * (1 - pt(2.45, df = 15))

```

**Question 2**

```{r}
# Leave keys.data alone. This is the provided sample data
keys.data <- c(0.30,0.24,0.19,0.17,0.18,0.23,0.24,0.06,0.15,0.17,0.18,0.17,
               0.15,0.12,0.25,0.25,0.25,0.32,0.35,0.37,0.39,0.46,0.49,0.42,0.36)

# Fill in the following variables appropriately
xbar_keys <- mean(keys.data)
s_keys <- sd(keys.data)
t_obs_keys <- (xbar_keys - 0.2) / (s_keys / sqrt(length(keys.data)))
pval_keys <- 2 * (1 - pt(abs(t_obs_keys), df = length(keys.data) - 1))
t_test_keys <- t.test(keys.data,
                      alternative = "two.sided",
                      mu = 0.2,
                      conf.level = 0.95)

# print the results from the t.test()
t_test_keys


```

**Question 3**

```{r}
transgenic <- c(38.8,39,39.7,40,40.8,40.9,41,41,41,42.5,42.6,43,43,43.4,43.5,43.5,43.8,
                44.4,44.7,44.7,44.7,45.3,45.7,45.8,46.4,46.5,46.6,46.7,46.7,46.8,46.9,
                47.1,47.1,47.1,47.3,47.6,47.7,48.1,48.3,49.3,49.3,49.8,50.3,50.9,52.1)
commercial <- c(36.7,37.1,38.9,39.5,39.5,39.8,40,40.2,40.3,40.5,40.5,40.7,41.1,41.2,
                41.5,41.5,41.6,41.6,41.7,42.4,43.1,43.3,43.3,43.4,43.7,44.1,44.2,45.2,
                45.3,45.4,46,46.1,46.4,46.6,46.6,46.9,47.3,47.5,48.1,48.2,48.4,48.6,49,
                49.1,49.3,49.6,50.1,50.2,50.4,50.6,52.2,53,55.5,56.4)

t_test_chickens <- t.test(transgenic,
                          commercial,
                          alternative = "two.sided",
                          mu = 0,
                          conf.level = 0.95,
                          var.equal = FALSE)

```

**Question 4**

```{r}
prop_test_trans <- prop.test(x = 48,
                             n = 60,
                             p = 0.70,
                             alternative = "greater",
                             conf.level = 0.95,
                             correct = FALSE)

```

### Submission Instructions

1.  Save this file. (Quick key combo for that is "control" (or "command" on a Mac) and "s")
2.  Run the following code chunk to produce a pdf.
3.  Both of these files are likely in the "Downloads" folder (unless you moved them). Check the contents of each file and upload both the Rmd and pdf files to Gradescope.

```{r, echo=FALSE ,eval=FALSE,purl=FALSE}
rstudioapi::documentSave(rstudioapi::getSourceEditorContext()$id)
rmarkdown::render(rstudioapi::getSourceEditorContext()$path,output_format = "pdf_document")
rstudioapi::viewer(gsub("\\.Rmd","\\.pdf",rstudioapi::getSourceEditorContext()$path))
```
